import "@/app/globals.css"; 
import Navbar from "@/Components/LandingPage/Common/Navbar";
import Footer from "@/Components/LandingPage/Common/Footer";

export const metadata = {
  title: "CoLivers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-white font-plus-jakarta text-black"
      >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
