import RootLayout from "../Components/RootLayout";

export const metadata = {
  title: "CoLivers",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return <RootLayout>{children}</RootLayout>;
}
